name: Dependabot Auto-Merge
on:
  pull_request_target:
  workflow_dispatch:
    inputs:
      pr_number:
        description: 'Dependabot pull request to verify and merge'
        required: true

permissions:
  contents: write
  pull-requests: write
  actions: write

jobs:
  dependabot:
    uses: zdro-tech/infrastructure-primitives-shared/.github/workflows/merge_dependabot_pr.yml@main
    with:
      pr_number: ${{ inputs.pr_number }}
    secrets:
      GITUB_SSH_KEY: ${{ secrets.GITUB_ACTIONS_SSH_DEV }}
