name: Update Lockfile
on:
  schedule:
    - cron: '0 0 * * 0' # Every Sunday at midnight
  workflow_dispatch:

permissions:
  contents: write
  actions: write

jobs:
  update-lockfile:
    uses: zdro-tech/infrastructure-primitives-shared/.github/workflows/refresh_lockfiles.yml@main
    secrets:
      GITUB_SSH_KEY: ${{ secrets.GITUB_ACTIONS_SSH_DEV }}
